# Users section
docker_user: "jarvis" # User responsible for running the containers
my_user: "mike" # My users that has been created earlier by CloudInit

# Groups section
data_group: "mike-data" # Group that owns the data and configs
